language: c

sudo: false

os:
  - linux
  - osx

env:
  global:
    - CONDA_DEPENDENCIES="cython numpy pytest"
    - PIP_DEPENDENCIES="hypothesis[numpy]"
  matrix:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.3
    - PYTHON_VERSION=3.4
    - PYTHON_VERSION=3.5
    - PYTHON_VERSION=3.6

install:
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh

script:
  - python setup.py build_ext --inplace
  - pytest fast_histogram

