language: c

sudo: false

os:
  - linux
  - osx

env:
  global:
    - CONDA_DEPENDENCIES="numpy pytest nomkl"
    - PIP_DEPENDENCIES="hypothesis[numpy]"
  matrix:
    - PYTHON_VERSION=2.7 NUMPY_VERSION=1.10
    - PYTHON_VERSION=2.7 NUMPY_VERSION=1.11
    - PYTHON_VERSION=3.5 NUMPY_VERSION=1.12
    - PYTHON_VERSION=3.6 NUMPY_VERSION=1.13
    - PYTHON_VERSION=3.6 NUMPY_VERSION=1.14
    - PYTHON_VERSION=3.7 NUMPY_VERSION=1.15
    - PYTHON_VERSION=3.7 NUMPY_VERSION=1.16

    # Do a build without Numpy to make sure it's automatically installed
    - PYTHON_VERSION=3.6 CONDA_DEPENDENCIES="pytest"

install:
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh

script:
  - LC_ALL=C python setup.py check --restructuredtext
  - python setup.py build_ext --inplace
  - pytest fast_histogram -p no:warnings --hypothesis-show-statistics
